version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hgomesu/rails-chat:latest
    container_name: rails_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "bundle install && rails db:setup && rails server -b 0.0.0.0"
    environment:
      - RAILS_ENV=development